# Generated by Django 4.0.6 on 2023-03-10 07:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AboutSectionTitleModel',
            fields=[
                ('titleName', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
                ('rank', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    )
                ),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('subject', models.CharField(blank=True, max_length=400, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    )
                ),
            ],
        ),
        migrations.CreateModel(
            name='MediaFileUploadModel',
            fields=[
                ('fileName', models.CharField(blank=True, max_length=50, null=True)),
                ('buttonTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('actualFile', models.FileField(blank=True, null=True, upload_to='')),
                ('is_downloadable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    )
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeCounterModel',
            fields=[
                ('counterTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('rank', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    )
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleNameModel',
            fields=[
                ('roleName', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    )
                ),
            ],
            options={
                'ordering': ['roleName'],
            },
        ),
        migrations.CreateModel(
            name='ShortIntroModel',
            fields=[
                ('introText', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    )
                ),
            ],
            options={
                'ordering': ['-is_active'],
            },
        ),
    ]
