# Generated by Django 5.1.4 on 2024-12-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutsectiontitlemodel',
            old_name='id',
            new_name='pkid',
        ),
        migrations.RenameField(
            model_name='contactmodel',
            old_name='id',
            new_name='pkid',
        ),
        migrations.RenameField(
            model_name='mediafileuploadmodel',
            old_name='id',
            new_name='pkid',
        ),
        migrations.RenameField(
            model_name='resumecountermodel',
            old_name='id',
            new_name='pkid',
        ),
        migrations.RenameField(
            model_name='rolenamemodel',
            old_name='id',
            new_name='pkid',
        ),
        migrations.RenameField(
            model_name='shortintromodel',
            old_name='id',
            new_name='pkid',
        ),
    ]
