name: Quality Assurance

# triggered when a pull request is made or called from another workflow
# in our deployment workflow we will call this workflow to run these checks before deploying
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    # human friendly display name
    name: Quality Assurance

    # this job will run on the latest version of Ubuntu available
    runs-on: ubuntu-latest

    # run inside a Python 3.10.4 Docker container, specifically one based on Debian Buster
    container: python:3.10.4-buster

    # section where background services needed by the job are defined (spun up in a separate Docker container)
    services:
      db:
        image: postgres:14.2-alpine
        env:
          POSTGRES_DB: myportfolio
          POSTGRES_USER: myportfolio
          POSTGRES_PASSWORD: myportfolio

    steps:
      # checks out the repository using the checkout action
      - uses: actions/checkout@v2

      - name: Install Git
        run: apt-get update && apt-get install -y git

      - name: Install Pre-commit
        run: pip install pre-commit

      - name: Verify Git Repository
        run: git status

      - name: Install Pre-commit Hooks
        run: pre-commit install

      - name: Debug Pre-commit Log
        if: failure()
        run: cat /github/home/.cache/pre-commit/pre-commit.log

      - name: Install Dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        env:
          PORTFOLIO_SETTINGS_DATABASES: '{"default":{"HOST":"db","PORT":"5432"}}'
          PORTFOLIO_SETTINGS_LOCAL_SETTINGS_PATH: './myportfolio/myportfolio/settings/template/settings.github.py'
